terraform {
  required_version = ">= 1.6.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  # Remote state. Values come from backend.conf (generated by bootstrap-azure.ps1):
  #   terraform init -backend-config=backend.conf
  backend "azurerm" {}
}

provider "azurerm" {
  subscription_id = var.subscription_id

  features {
    resource_group {
      # The exercise environment is disposable - let destroy clean up stragglers
      prevent_deletion_if_contains_resources = false
    }
  }
}

data "azurerm_client_config" "current" {}

locals {
  name = "${var.prefix}-${var.environment}"

  tags = {
    project     = "wiz-technical-exercise"
    environment = var.environment
    managed_by  = "terraform"
    owner       = var.owner_tag
  }
}
